Repository tmax-cloud/argocd-installer, pull requests merged in 2022-10, with the labels that each got.

#246 [fix] dashboard console url
  application/helm/templates/grafana-operator.yaml
  manifest/grafana-operator/grafana-operator-dashboard-cm.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: bug

#248 add gitlab pvc
  application/helm/templates/gitlab.yaml
  manifest/gitlab/templates/deployment.yaml
  manifest/gitlab/values.yaml
Labels: enhancement

#249 [update] grafana-operator jasonnet
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: invalid

#243 [add] Loki stack application/helm & manifest 추가
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/loki.yaml
  manifest/loki/README.md
  manifest/loki/loki-config.yaml
  manifest/loki/loki-promtail.jsonnet
  manifest/loki/loki-sa-service.yaml
  manifest/loki/promtail-clusterrolebinding.yaml
  manifest/loki/promtail-config.yaml
Labels: enhancement, release-v1.1

#252 fix loki error
  [
  manifest/loki/loki-config.yaml
Labels: bug

#256 version upgrade 및 error 처리
  application/helm/templates/gitlab.yaml
  manifest/hyperauth/hyperauth.jsonnet
  manifest/hypercloud/hypercloud-api-server.jsonnet
Labels: bug, enhancement

#258 [cicd-operator] update cicd-operator version to v0.4.13
  manifest/cicd-operator/cicd-operator.jsonnet
Labels: version

#255 [Hperregistry] refactor: synchronized with kubespary deploy
  manifest/hyperregistry/values.yaml
Labels: enhancement

#259 argocd-installer error fix
  application/helm/templates/_template.tpl
  manifest/gitlab/templates/deployment.yaml
  manifest/grafana-operator/grafana-operator-cert.yaml
  manifest/helm-apiserver/helm-apiserver.yaml
Labels: bug

#260 [helm-apiserver] image version update
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/helm-apiserver/helm-apiserver.jsonnet
Labels: bug, version

#262 argocd error 수정 및 요청 반영
  application/helm/master-values.yaml
  application/helm/shared-values.yaml
  application/helm/single-values.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/gateway/gateway-values-nodeport.yaml
  manifest/api-gateway/gateway/gateway-values.yaml
  manifest/api-gateway/jwt-decode-auth/jwt-decode-auth-values.yaml
Labels: bug, enhancement

#263 [IMS #288384] grafana-operator 폐쇠망, 이슈 반영
  application/helm/templates/grafana-operator.yaml
  manifest/grafana-operator/grafana-operator-rbac.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: enhancement, IMS, version

#265 [feat] add setting bind-address to 0.0.0.0 in capi-template
  manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
Labels: enhancement, version

#268 argocd에서 dex 제거
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/argocd.yaml
  manifest/argocd/templates/deployment.yaml
  manifest/argocd/templates/networkpolicy.yaml
  manifest/argocd/templates/role.yaml
  manifest/argocd/templates/rolebinding.yaml
  manifest/argocd/templates/secret.yaml
  manifest/argocd/templates/service.yaml
  manifest/argocd/templates/serviceaccounts.yaml
  manifest/argocd/values.yaml
Labels: enhancement

#270 [gitlab] edit gitlab manifest typo
  manifest/gitlab/templates/deployment.yaml
Labels: bug

#269 [cicd-operator] add jar build Tekton task
  manifest/cicd-operator/gradle-build-task.yaml
  manifest/cicd-operator/maven-build-task.yaml
Labels: enhancement

#271 argocd namespace 추가
  application/helm/templates/argocd.yaml
  application/helm/templates/service-binding-operator.yaml
  manifest/argocd/templates/namespace.yaml
Labels: enhancement

#272 Update clustermenupolicy.yaml
  manifest/api-gateway/console/crds/clustermenupolicy.yaml
Labels: IMS

#274 [feat] console 5.0.82.2 version update
  manifest/api-gateway/console/console-values.yaml
Labels: release-v1.1, version

#275 [fix] gitlab appsync error
  manifest/gitlab/templates/deployment.yaml
Labels: bug

#276 [fix] gitlab - 잘못된 externalURL error
  application/helm/templates/gitlab.yaml
Labels: bug

#278 [mod] redis operator 버전 업그레이드
  manifest/redis-operator/redis-operator.jsonnet
Labels: bug, version

#282 opensearch secret 제거 및 ims 291686 cmp sample 추가
  manifest/api-gateway/console/templates/cmp-default-menus-sample.yaml
  manifest/opensearch/opensearch-ingress.jsonnet
Labels: bug, IMS

#283 [mod] sample cmp 수정
  manifest/api-gateway/console/templates/cmp-default-menus-sample.yaml
Labels: bug, invalid

#284 [IMS][291653] argocd-installer 내 모듈 버전 업 요청
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  docs/INSTALL_ORDER.md
  manifest/api-gateway/console/Chart.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/jwt-decode-auth/templates/deployment.yaml
  manifest/api-gateway/jwt-decode-auth/values.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/nfs-subdir-external-provisioner/values.yaml
  manifest/service-binding-operator/service-binding-operator.jsonnet
Labels: bug, IMS, version

#290 [feat] hypercloud-multi-operator version up:b5.0.34.5
  manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
Labels: enhancement, IMS, version

#291 [mod] argocd-installer doc update
  docs/INSTALL_GUIDE_SINGLE.md
  docs/INSTALL_MODULE_LIST.md
  docs/INSTALL_ORDER.md
Labels: documentation

#293 [mod] multi-operator 5.0.34.5 version capi cluster template 수정
  manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
Labels: bug

#295 fix argocd manifest error
  application/helm/templates/aws-efs-csi-driver.yaml
  manifest/gitlab/templates/deployment.yaml
Labels: bug

#294 [cicd-operator] fix jar build sample TektonTask
  manifest/cicd-operator/gradle-build-task.yaml
  manifest/cicd-operator/maven-build-task.yaml
Labels: IMS

#296 [mod] add hypercloud=system label to namespace
  manifest/api-gateway/namespace/namespaces.yaml
  manifest/argocd/templates/namespace.yaml
  manifest/catalog-controller/catalog-controller.yaml
  manifest/cert-manager/install.yaml
  manifest/cicd-operator/cicd-operator.yaml
  manifest/cluster-api-provider-aws/infrastructure-components-aws-v0.6.5.yaml
  manifest/cluster-api-provider-vsphere/infrastructure-components-vsphere-v0.7.6.yaml
  manifest/cluster-api/cluster-api-components-v0.3.16.yaml
  manifest/efk/efk-namespace-serviceaccount.yaml
  manifest/gitlab/templates/deployment.yaml
  manifest/helm-apiserver/helm-apiserver.yaml
  manifest/hyperauth/initialization.yaml
  manifest/hypercloud/init.yaml
  manifest/hyperregistry/templates/namespace.yaml
  manifest/image-validating-webhook/image-validating-webhook.yaml
  manifest/opensearch/opensearch-namespace-serviceaccount.yaml
  manifest/prometheus/0namespace-namespace.yaml
  manifest/redis-operator/namespace.yaml
  manifest/service-binding-operator/service-binding-operator.yaml
  manifest/service-mesh/istio/2.istio-base.yaml
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
  manifest/tekton-pipeline/tekton-pipeline.yaml
  manifest/template-service-broker/template-service-broker.yaml
Labels: enhancement

#297 [mod] hyperauth ingress에 secret 제거
  manifest/hyperauth/hyperauth.jsonnet
Labels: bug
