Repository tmax-cloud/argocd-installer, pull requests merged in 2022-12, with the labels that each got.

#329 update nsdashboatd (limit request)
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: bug

#330 [feat] add github action testing pr
  .github/workflows/verify.yml
Labels: enhancement

#333 hyperauth self-signed bug 처리 / traefik nlb internal 값 false로 변경
  application/helm/templates/hyperauth.yaml
  manifest/api-gateway/gateway/gateway-values-nodeport.yaml
  manifest/api-gateway/gateway/gateway-values.yaml
  manifest/api-gateway/gateway/values.yaml
  manifest/hyperauth/hyperauth.jsonnet
  manifest/hyperauth/kafka.jsonnet
Labels: bug, enhancement

#334 cicd-operator 0.4.14, console 5.0.86.5 version up
  manifest/api-gateway/console/Chart.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/console/values.yaml
  manifest/cicd-operator/cicd-operator.jsonnet
Labels: version

#335 [feat] cicd blocker 0.4.14 version up
  manifest/cicd-operator/cicd-operator.jsonnet
Labels: version

#338 [feat] console 5.0.87.1 version up
  manifest/api-gateway/console/Chart.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/console/values.yaml
Labels: version

#337 add nexus (ims-294099)
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/nexus.yaml
  manifest/nexus/.helmignore
  manifest/nexus/Chart.yaml
  manifest/nexus/LICENSE
  manifest/nexus/README.md
  manifest/nexus/templates/NOTES.txt
  manifest/nexus/templates/_helpers.tpl
  manifest/nexus/templates/configmap-properties.yaml
  manifest/nexus/templates/configmap.yaml
  manifest/nexus/templates/deployment.yaml
  manifest/nexus/templates/ingress.yaml
  manifest/nexus/templates/namespace.yaml
  manifest/nexus/templates/pvc.yaml
  manifest/nexus/templates/secret.yaml
  manifest/nexus/templates/service.yaml
  manifest/nexus/templates/serviceaccount.yaml
  manifest/nexus/templates/test/test-check-logs.yaml
  manifest/nexus/templates/test/test-connection.yaml
  manifest/nexus/tests/deployment_test.yaml
  manifest/nexus/tests/ingress_test.yaml
  manifest/nexus/values.yaml
Labels: IMS

#339 [fix] nexus 하위 앱에 잘못된 표기 수정 및 sc 사용 추가
  .github/workflows/verify.yml
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/nexus.yaml
Labels: bug

#340 [feat] workflow가 master, single에서 반드시 실행되도록 수정 / 주석 추가 /특정 모듈 사용 기능 추가
  .github/workflows/verify.yml
Labels: enhancement

#336 [ims][294948][294952] redis, kafka CRD 국문화
  manifest/redis-operator/redis-cluster-crd.yaml
  manifest/redis-operator/redis-standalone-crd.yaml
  manifest/strimzi-kafka-cluster-operator/kafka-crd-key-mapping.yaml
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
Labels: IMS

#332 update validation webhook config for k8s 1.25 version
  manifest/grafana-operator/grafana-operator-validationwebhookconf.yaml
Labels: enhancement

#218 Update HyperAuth LogLevel
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/hyperauth.yaml
  manifest/hyperauth/hyperauth.jsonnet
Labels: loglevel

#216 Modify catalog controller v level
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/catalog-controller.yaml
  manifest/catalog-controller/catalog-controller.jsonnet
Labels: loglevel

#217 Update ServiceMesh loglevel (istio, jaeger, kiali)
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/istio.yaml
  application/helm/templates/jaeger.yaml
  application/helm/templates/kiali.yaml
  manifest/service-mesh/istio/5.istio-deploy.jsonnet
  manifest/service-mesh/istio/5.istio-sidecar-configmap.jsonnet
  manifest/service-mesh/jaeger/7.jaeger.jsonnet
  manifest/service-mesh/kiali/8.kilai.jsonnet
Labels: loglevel

#341 [fix] fix log level error(catalog, service mesh, hyperauth)
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/catalog-controller.yaml
  application/helm/templates/hyperauth.yaml
  application/helm/templates/kiali.yaml
  manifest/catalog-controller/catalog-controller.jsonnet
  manifest/hyperauth/hyperauth.jsonnet
  manifest/hyperauth/kafka.jsonnet
  manifest/service-mesh/istio/5.istio-deploy.jsonnet
  manifest/service-mesh/istio/5.istio-sidecar-configmap.jsonnet
  manifest/service-mesh/kiali/8.kilai.jsonnet
Labels: bug

#214 [template-service-broker] Loglevel 설정
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/template-service-broker.yaml
  manifest/template-service-broker/tsb-deployment.jsonnet
Labels: enhancement, loglevel, version

#342 [feat] fix log level in tsb / add log level to redis operator
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/redis-operator.yaml
  manifest/redis-operator/redis-operator.jsonnet
  manifest/template-service-broker/tsb-deployment.jsonnet
Labels: bug, enhancement

#344 [feat] git action flow update
  .github/template/root-applications.yaml
  .github/workflows/verify.yml
Labels: enhancement

#343 add sonarqube
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/sonarqube/.helmignore
  manifest/sonarqube/Chart.yaml
  manifest/sonarqube/templates/_helpers.tpl
  manifest/sonarqube/templates/namespace.yaml
  manifest/sonarqube/templates/service-account.yaml
  manifest/sonarqube/templates/sonarqube-conf-pvc.yaml
  manifest/sonarqube/templates/sonarqube-data-pvc.yaml
  manifest/sonarqube/templates/sonarqube-ingress.yaml
  manifest/sonarqube/templates/sonarqube-logs-pvc.yaml
  manifest/sonarqube/templates/sonarqube-service.yaml
  manifest/sonarqube/templates/sonarqube.yaml
  manifest/sonarqube/values.yaml
Labels: enhancement, IMS, module

#345 Add sonarqube app
  .github/template/root-applications.yaml
  application/helm/templates/sonarqube.yaml
  manifest/sonarqube/templates/service-account.yaml
  manifest/sonarqube/values.yaml
Labels: bug

#346 [feat] update git action workflow
  .github/template/root-applications.yaml
  .github/workflows/verify.yml
Labels: enhancement

#347 cicd-operator CRD version 0.4.14
  manifest/cicd-operator/cicd-operator.yaml
  manifest/tekton-pipeline/tekton-pipeline.yaml
Labels: enhancement, IMS

#351 [fix] api-gateway error fix
  .github/template/root-applications.yaml
  .github/workflows/verify.yml
  application/app_of_apps/master-applications.yaml
  application/helm/master-values.yaml
  application/helm/shared-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/api-gateway-console.yaml
  application/helm/templates/api-gateway-gateway.yaml
  application/helm/templates/api-gateway-jwt-decode-auth.yaml
  application/helm/templates/api-gateway-oauth2-proxy.yaml
  application/helm/templates/cert-manager.yaml
  application/helm/templates/hyperauth.yaml
  application/helm/templates/strimzi-kafka-operator.yaml
  manifest/api-gateway/oauth2-proxy/templates/_helpers.tpl
  manifest/api-gateway/oauth2-proxy/templates/deployment.yaml
  manifest/hyperauth/hyperauth.jsonnet
Labels: bug, enhancement
