Repository tmax-cloud/argocd-installer, pull requests merged in 2022-09, with the labels that each got.

#224 [Hyperregistry] fix to set timezone for redis, trivy
  manifest/hyperregistry/templates/redis/statefulset.yaml
  manifest/hyperregistry/templates/trivy/trivy-sts.yaml
Labels: timezone

#228 feat: add servicebinding
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/service-binding-operator.yaml
  manifest/service-binding-operator/service-binding-operator.jsonnet
  manifest/service-binding-operator/service-binding-operator.yaml
Labels: enhancement, timezone, release-v1.1

#204 [hypercloud] version-config에서 kibana -> opensearch 변경
  manifest/hypercloud/hypercloud-api-server.jsonnet
Labels: enhancement, release-v1.1

#180 update jwt-decode and console
  docs/API-GATEWAY.md
  manifest/api-gateway-bootstrap/templates/console.yaml
  manifest/api-gateway-bootstrap/values.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/console/templates/deployment.yaml
  manifest/api-gateway/console/values.yaml
  manifest/api-gateway/gateway/templates/secrets.yaml
  manifest/api-gateway/jwt-decode-auth/Chart.yaml
  manifest/api-gateway/jwt-decode-auth/jwt-decode-auth-values.yaml
  manifest/api-gateway/jwt-decode-auth/templates/deployment.yaml
  manifest/api-gateway/jwt-decode-auth/values.yaml
Labels: enhancement, release-v1.1

#185 [grafana-operator] grafana operator 추가 및 hypercloud의 grafana 관련 로직 제거된 이미지로 변경
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/grafana.yaml
  manifest/grafana-operator/README.md
  manifest/grafana-operator/grafana-operator-cert.yaml
  manifest/grafana-operator/grafana-operator-crd.yaml
  manifest/grafana-operator/grafana-operator-dashboard-cm.yaml
  manifest/grafana-operator/grafana-operator-datasource.yaml
  manifest/grafana-operator/grafana-operator-rbac.yaml
  manifest/grafana-operator/grafana-operator-svc.yaml
  manifest/grafana-operator/grafana-operator-validationwebhookconf.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-single-operator.jsonnet
Labels: enhancement, timezone, release-v1.1

#233 grafana operator timezone 추가 및 에러 처리
  application/helm/templates/grafana-operator.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-single-operator.jsonnet
Labels: bug, timezone

#219 [hyperregistry] IMS#289299 - feat: enable hyperregistry oidc
  application/helm/templates/hyperregistry.yaml
  manifest/hyperregistry/templates/core/core-cm.yaml
  manifest/hyperregistry/templates/core/core-dpl.yaml
  manifest/hyperregistry/values.yaml
Labels: enhancement, IMS#289299, release-v1.1

#234 hyperregistry manifest error 수정 및 hypercloud multi-operator version upgrade
  application/helm/templates/hyperregistry.yaml
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
Labels: bug, enhancement

#237 [feat] hypercloud timescaledb 전환, 로그레벨 적용
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/hypercloud.yaml
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-single-operator.jsonnet
  manifest/hypercloud/postgres.jsonnet
  manifest/hypercloud/postgres.yaml
  manifest/hypercloud/timescaledb.jsonnet
  manifest/hypercloud/timescaledb.yaml
  manifest/hypercloud/webhook-configuration.yaml
Labels: enhancement, loglevel, release-v1.1

#238 Calico CNI Jsonnet
  .DS_Store
  application/.DS_Store
  application/app_of_apps/single-applications.yaml
  application/helm/.DS_Store
  application/helm/single-values.yaml
  application/helm/templates/calico.yaml
  manifest/.DS_Store
  manifest/calico/.DS_Store
  manifest/calico/calico.jsonnet
Labels: enhancement, release-v1.1

#235 [mod] hypercloud multi-operator b5.0.34.0 version upgrade
  application/app_of_apps/single-applications.yaml
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/hypercloud.yaml
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
  manifest/hypercloud/hypercloud-single-operator.jsonnet
  manifest/hypercloud/timescaledb.jsonnet
Labels: enhancement, loglevel

#236 gitlab master cluster 등록IMS-285349
  application/helm/templates/gitlab.yaml
Labels: enhancement, IMS

#241 [mod] calico error fix / single 및 master values에 허용 모듈 변경 / api-gateway-bootstrap autosync 제거
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/api-gateway-bootstrap.yaml
  manifest/calico/calico.jsonnet
Labels: bug, enhancement

#245 update helm apiserver version
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/helm-apiserver/helm-apiserver.jsonnet
Labels: bug, enhancement, release-v1.1

#242 [fix] grafana-operator version, grafana version, dashboard linkUrl
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/grafana-operator/grafana-operator-config.yaml
  manifest/grafana-operator/grafana-operator-dashboard-cm.yaml
  manifest/grafana-operator/grafana-operator-datasource-loki.yaml
  manifest/grafana-operator/grafana-operator-datasource-prometheus.yaml
  manifest/grafana-operator/grafana-operator-validationwebhookconf.yaml
  manifest/grafana-operator/grafana-operator.jsonnet
  manifest/grafana/grafana.jsonnet
Labels: enhancement, release-v1.1
