Repository tmax-cloud/argocd-installer, pull requests merged in 2022-11, with the labels that each got.

#300 [chore] update cicd-operator.yaml version to v0.4.13
  manifest/cicd-operator/cicd-operator.yaml
Labels: version

#303 [chore] update cicd-operator version to v0.4.13
  manifest/cicd-operator/cicd-operator.yaml
Labels: bug

#302 [add] hypercloud-api-server kubectl CLI 기능을 위한 KUBECTL_TIMEOUT 환경변수 추가
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/hypercloud.yaml
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-single-operator.jsonnet
  manifest/hypercloud/timescaledb.jsonnet
Labels: IMS, version

#301 [ims][293381] kafka 관련 CRD 필수 스펙 변경
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
Labels: bug, IMS

#305 Update grafana-operator.jsonnet client id, client secret
  manifest/grafana-operator/grafana-operator.jsonnet
  manifest/grafana-operator/node-dashboard.yaml
Labels: enhancement

#306 [ims][292565] 웹훅 데드락 해결을 위한 웹훅 예외처리
  manifest/hypercloud/webhook-configuration.yaml
Labels: enhancement, IMS

#307 깃랩 OIDC연동
  manifest/gitlab/templates/deployment.yaml
  manifest/gitlab/values.yaml
Labels: enhancement

#311 [feat] gitea namespace 추가
  manifest/gitea/templates/gitea/namespace.yaml
Labels: bug

#312 [mod] fix manifest error
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: bug

#314 Update grafana-operator.jsonnet node dashboard
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: enhancement

#315 update helm apiserver version
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/helm-apiserver/helm-apiserver.jsonnet
Labels: version

#319 [mod] fix grafana-operator manifest error
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: bug

#318 update console version to 5.0.83.0
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/console/values.yaml
Labels: version

#320 [version] hyercloud api server, single operator version up
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-single-operator.jsonnet
Labels: version

#321 [fix] grafana-operator node-dashboard
  manifest/grafana-operator/grafana-operator.jsonnet
Labels: enhancement

#322 [mod] disable gitea
  application/helm/master-values.yaml
  application/helm/single-values.yaml
Labels: enhancement

#323 hypercloud version up 5.0.37.x
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-upgrade-template.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
Labels: version

#324 ai devops 모듈 제거 / single operator 5.0.37.0 version up
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/ai-devops.yaml
  manifest/ai-devops/1.cluster-local-gateway.jsonnet
  manifest/ai-devops/10.pytorchjob.jsonnet
  manifest/ai-devops/11.tfjob.jsonnet
  manifest/ai-devops/12.knative.jsonnet
  manifest/ai-devops/2.kubeflow-istio-resources.jsonnet
  manifest/ai-devops/3.add-anonymous-user-filter.jsonnet
  manifest/ai-devops/4.application.jsonnet
  manifest/ai-devops/5.kubeflow-apps.jsonnet
  manifest/ai-devops/6.katib.jsonnet
  manifest/ai-devops/7.kfserving.jsonnet
  manifest/ai-devops/8.minio.jsonnet
  manifest/ai-devops/9.notebook.jsonnet
  manifest/ai-devops/README.md
  manifest/hypercloud/hypercloud-single-operator.jsonnet
Labels: enhancement, version

#325 console version to 5.0.84.1
  manifest/api-gateway/console/Chart.yaml
  manifest/api-gateway/console/console-values.yaml
  manifest/api-gateway/console/values.yaml
Labels: version

#326 [mod] gateway helm hook 제거
  manifest/api-gateway/gateway/templates/certificate.yaml
  manifest/api-gateway/gateway/templates/issuer.yaml
  manifest/api-gateway/gateway/templates/pre-install.yaml
  manifest/api-gateway/gateway/templates/secrets.yaml
  manifest/api-gateway/gateway/templates/tls-store.yaml
Labels: bug

#327 [mod] change gitlab oidc enabled to false
  application/helm/master-values.yaml
  application/helm/single-values.yaml
Labels: bug
