Repository tmax-cloud/argocd-installer, pull requests merged in 2022-08, with the labels that each got.

#192 Add timezone redis-operator
  application/helm/templates/otcontainerkit-operator.yaml
  manifest/otcontainerkit-redis-operator/otcontainerkit-operator.jsonnet
Labels: timezone

#193 EFK, Opensearch 모듈 timezone 설정
  application/helm/templates/efk.yaml
  application/helm/templates/opensearch.yaml
  manifest/efk/efk.jsonnet
  manifest/opensearch/opensearch-fluentd.jsonnet
  manifest/opensearch/opensearch-ingress.jsonnet
  manifest/opensearch/opensearch-securityconfig.jsonnet
Labels: timezone

#195 [hyperregistry, image-validation-webhook] Timezone 설정
  application/helm/templates/hyperregistry.yaml
  application/helm/templates/image-validating-webhook.yaml
  manifest/hyperregistry/templates/chartmuseum/chartmuseum-dpl.yaml
  manifest/hyperregistry/templates/core/core-dpl.yaml
  manifest/hyperregistry/templates/database/database-ss.yaml
  manifest/hyperregistry/templates/exporter/exporter-dpl.yaml
  manifest/hyperregistry/templates/jobservice/jobservice-dpl.yaml
  manifest/hyperregistry/templates/nginx/deployment.yaml
  manifest/hyperregistry/templates/notary/notary-server.yaml
  manifest/hyperregistry/templates/notary/notary-signer.yaml
  manifest/hyperregistry/templates/portal/deployment.yaml
  manifest/hyperregistry/templates/redis/statefulset.yaml
  manifest/hyperregistry/templates/registry/registry-dpl.yaml
  manifest/hyperregistry/templates/trivy/trivy-sts.yaml
  manifest/hyperregistry/values.yaml
  manifest/image-validating-webhook/image-validating-webhook.jsonnet
Labels: timezone

#196 Add service-mesh timezone
  application/helm/templates/istio.yaml
  application/helm/templates/jaeger.yaml
  application/helm/templates/kiali.yaml
  manifest/service-mesh/istio/5.istio-deploy.jsonnet
  manifest/service-mesh/jaeger/7.jaeger.jsonnet
  manifest/service-mesh/kiali/8.kilai.jsonnet
Labels: timezone

#197 [kafka] TimeZone 설정 추가
  application/helm/templates/strimzi-kfka-operator.yaml
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.jsonnet
Labels: timezone

#198 [ai-devops] kfserving image repo 변경(gcr.io -> docker.io) 및 time_zone 설정 추가
  application/helm/templates/ai-devops.yaml
  manifest/ai-devops/1.cluster-local-gateway.jsonnet
  manifest/ai-devops/10.pytorchjob.jsonnet
  manifest/ai-devops/11.tfjob.jsonnet
  manifest/ai-devops/12.knative.jsonnet
  manifest/ai-devops/2.kubeflow-istio-resources.jsonnet
  manifest/ai-devops/3.add-anonymous-user-filter.jsonnet
  manifest/ai-devops/4.application.jsonnet
  manifest/ai-devops/5.kubeflow-apps.jsonnet
  manifest/ai-devops/6.katib.jsonnet
  manifest/ai-devops/7.kfserving.jsonnet
  manifest/ai-devops/8.minio.jsonnet
  manifest/ai-devops/9.notebook.jsonnet
Labels: enhancement, timezone

#199 [add] prometheus grafana timezone 설정 반영
  application/helm/templates/grafana.yaml
  application/helm/templates/prometheus.yaml
  manifest/grafana/grafana.jsonnet
  manifest/prometheus/prometheus.jsonnet
Labels: timezone

#200 [hyperauth] timeZone 설정 추가, serviceAccount 설정 변경
  application/helm/templates/hyperauth.yaml
  manifest/hyperauth/hyperauth.jsonnet
  manifest/hyperauth/initialization.yaml
Labels: enhancement, timezone

#202 [feat] update timezone of gateway, jwt-decode-auth, console & 네임스페이스 생성 추가
  application/helm/templates/api-gateway-bootstrap.yaml
  manifest/api-gateway-bootstrap/templates/console.yaml
  manifest/api-gateway-bootstrap/templates/gateway.yaml
  manifest/api-gateway-bootstrap/templates/jwt-decode-auth.yaml
  manifest/api-gateway-bootstrap/templates/namespaces.yaml
  manifest/api-gateway-bootstrap/values.yaml
  manifest/api-gateway/console/templates/deployment.yaml
  manifest/api-gateway/console/values.yaml
  manifest/api-gateway/gateway/charts/traefik-10.9.1.tgz
  manifest/api-gateway/gateway/charts/traefik/values.yaml
  manifest/api-gateway/gateway/values.yaml
  manifest/api-gateway/jwt-decode-auth/jwt-decode-auth-values.yaml
  manifest/api-gateway/jwt-decode-auth/templates/deployment.yaml
  manifest/api-gateway/jwt-decode-auth/values.yaml
  manifest/api-gateway/namespace/namespaces.yaml
Labels: enhancement, timezone

#179 Add argocd manifest
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/argocd.yaml
  manifest/argocd/.helmignore
  manifest/argocd/Chart.yaml
  manifest/argocd/templates/clusterrole.yaml
  manifest/argocd/templates/clusterrolebinding.yaml
  manifest/argocd/templates/configmap.yaml
  manifest/argocd/templates/crd-application.yaml
  manifest/argocd/templates/crd-project.yaml
  manifest/argocd/templates/deployment.yaml
  manifest/argocd/templates/ingress.yaml
  manifest/argocd/templates/networkpolicy.yaml
  manifest/argocd/templates/role.yaml
  manifest/argocd/templates/rolebinding.yaml
  manifest/argocd/templates/secret.yaml
  manifest/argocd/templates/service.yaml
  manifest/argocd/templates/serviceaccounts.yaml
  manifest/argocd/templates/statefulset.yaml
  manifest/argocd/values.yaml
Labels: enhancement
