Repository tmax-cloud/argocd-installer, pull requests merged in 2023-02, with the labels that each got.

#378 [feat] strimzi kafka operator 0.32.0 버전 업그레이드
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  manifest/hyperauth/kafka.jsonnet
  manifest/strimzi-kafka-cluster-operator/kafka-crd-key-mapping.yaml
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.jsonnet
  manifest/strimzi-kafka-cluster-operator/strimzi-cluster-operator.yaml
Labels: version

#412 [fix] notebook-controller gatekeeper image 폐쇄망일경우 적용 및 이미지 버전 업데이트
  manifest/ai-devops/10.notebook.jsonnet
Labels: IMS, version

#410 [feat] k8s 1.25버전 호환을 위한 hypercloud-single-operator CRD v1 업그레이드
  manifest/hypercloud/hypercloud-single-operator.yaml
Labels: version, v1.25

#388 gitea - k8s 1.25v manifest 반영
  manifest/gitea/values.yaml
Labels: v1.25

#419 [IMS][298287] single-mode로 설치시, multi관련 리소스 배포되는 이슈 - v5.1.1
  application/helm/templates/hypercloud.yaml
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
  manifest/hypercloud/hypercloud-single-operator.jsonnet
  manifest/hypercloud/timescaledb.jsonnet
Labels: bug, IMS

#418 [IMS][298287] single-mode로 설치시, multi관련 리소스 배포되는 이슈 - v5.1.0
  application/helm/templates/hypercloud.yaml
  manifest/hypercloud/hypercloud-api-server.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
  manifest/hypercloud/hypercloud-single-operator.jsonnet
Labels: bug, IMS

#372 loglevel 변수화 - tekton-pipeline, tekton-triggers, gitlab, gitea, sonarqube, nexus
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/gitea.yaml
  application/helm/templates/gitlab.yaml
  application/helm/templates/nexus.yaml
  application/helm/templates/sonarqube.yaml
  application/helm/templates/tekton-pipeline.yaml
  application/helm/templates/tekton-trigger.yaml
  manifest/gitea/values.yaml
  manifest/gitlab/templates/deployment.yaml
  manifest/gitlab/values.yaml
  manifest/nexus/Chart.yaml
  manifest/nexus/templates/deployment.yaml
  manifest/nexus/values.yaml
  manifest/sonarqube/templates/sonarqube.yaml
  manifest/sonarqube/values.yaml
  manifest/tekton-pipeline/tekton-pipeline.jsonnet
  manifest/tekton-pipeline/tekton-pipeline.yaml
  manifest/tekton-trigger/tekton-trigger.jsonnet
  manifest/tekton-trigger/tekton-trigger.yaml
Labels: loglevel

#436 [fix] multi-operator error 수정 - release-v5.1.0
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
Labels: bug

#437 [fix] multi-operator error 수정 - release-v5.1.1
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
Labels: bug

#441 [IMS][298480] argocd-installer v1.25 hypercloud single 모드 설치 시 연관 crd 에러
  manifest/hypercloud/hypercloud-single-operator.yaml
Labels: bug, IMS

#443 [mod] single operator validatingwebhookconfiguration 수정
  manifest/hypercloud/hypercloud-single-operator.yaml
Labels: bug

#477 [CAPI] add resource limit and request - main
  manifest/cluster-api/templates/capi-aws/deployment.yaml
  manifest/cluster-api/templates/capi-vsphere/deployment.yaml
  manifest/cluster-api/templates/capi/deployment.yaml
  manifest/cluster-api/values.yaml
Labels: enhancement

#473 [CAPI] add resource limit and request - v5.1.1
  manifest/cluster-api-provider-aws/cluster-api-provider-aws.jsonnet
  manifest/cluster-api-provider-vsphere/cluster-api-provider-vsphere.jsonnet
  manifest/cluster-api/cluster-api.jsonnet
Labels: enhancement

#472 [CAPI] add resource limit and request - v5.1.0
  manifest/cluster-api-provider-aws/cluster-api-provider-aws.jsonnet
  manifest/cluster-api-provider-vsphere/cluster-api-provider-vsphere.jsonnet
  manifest/cluster-api/cluster-api.jsonnet
Labels: enhancement
