Repository tmax-cloud/argocd-installer, pull requests merged in 2023-01, with the labels that each got.

#352 [feat] gateway, certmanager autosync enable 기능 추가
  .github/template/root-applications.yaml
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/api-gateway-console.yaml
  application/helm/templates/api-gateway-gateway.yaml
  application/helm/templates/api-gateway-jwt-decode-auth.yaml
  application/helm/templates/api-gateway-oauth2-proxy.yaml
  application/helm/templates/cert-manager.yaml
Labels: enhancement

#356 gitea - add oauth default value
  manifest/gitea/templates/_helpers.tpl
  manifest/gitea/values.yaml
  manifest/nexus/templates/ingress.yaml
  manifest/nexus/values.yaml
  manifest/tekton-pipeline/tekton-pipeline.yaml
Labels: bug

#353 [tekton-pipeline] fix flag disable-affinity-assistant to true
  manifest/tekton-pipeline/tekton-pipeline.yaml
Labels: bug

#358 sonarqube - [fix] pvc 생성 에러 수정, 버전업 9.8.0-community
  manifest/sonarqube/templates/sonarqube-conf-pvc.yaml
  manifest/sonarqube/templates/sonarqube-data-pvc.yaml
  manifest/sonarqube/templates/sonarqube-ingress.yaml
  manifest/sonarqube/templates/sonarqube-logs-pvc.yaml
  manifest/sonarqube/values.yaml
Labels: bug, version

#370 [Image-Validating-Webhook] set pod resources, loglevel
  manifest/image-validating-webhook/image-validating-webhook.jsonnet
Labels: loglevel

#375 [Hyperregistry] set pod resources, default loglevel
  manifest/hyperregistry/values.yaml
Labels: loglevel

#374 gateway nlb 생성 방식(private=> public)수정
  manifest/api-gateway/gateway/values.yaml
Labels: bug, enhancement

#377 cluster api version upgrade 및 helm chart로 변경
  .github/template/root-applications.yaml
  application/helm/master-values.yaml
  application/helm/single-values.yaml
  application/helm/templates/cluster-api-provider-aws.yaml
  application/helm/templates/cluster-api-provider-vsphere.yaml
  application/helm/templates/cluster-api.yaml
  application/helm/templates/hypercloud.yaml
  manifest/cluster-api-provider-aws/cluster-api-provider-aws.jsonnet
  manifest/cluster-api-provider-aws/infrastructure-components-aws-v0.6.5.yaml
  manifest/cluster-api-provider-vsphere/cluster-api-provider-vsphere.jsonnet
  manifest/cluster-api-provider-vsphere/infrastructure-components-vsphere-v0.7.6.yaml
  manifest/cluster-api/.helmignore
  manifest/cluster-api/Chart.yaml
  manifest/cluster-api/cluster-api-components-v0.3.16.yaml
  manifest/cluster-api/cluster-api.jsonnet
  manifest/cluster-api/templates/_helpers.tpl
  manifest/cluster-api/templates/capi-aws/credentials.yaml
  manifest/cluster-api/templates/capi-aws/deployment.yaml
  manifest/cluster-api/templates/capi-aws/etc.yaml
  manifest/cluster-api/templates/capi-vsphere/credentials.yaml
  manifest/cluster-api/templates/capi-vsphere/deployment.yaml
  manifest/cluster-api/templates/capi-vsphere/etc.yaml
  manifest/cluster-api/templates/capi/deployment.yaml
  manifest/cluster-api/templates/capi/etc.yaml
  manifest/cluster-api/values.yaml
Labels: enhancement, loglevel, version

#387 [feat] hypercloud multi-operator 5.1.1.0 version update
  manifest/hypercloud/hypercloud-capi-aws-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
  manifest/hypercloud/hypercloud-capi-vsphere-upgrade-template.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
  manifest/hypercloud/hypercloud-multi-operator.yaml
Labels: enhancement, version

#400 [etc] multi-operator image version 수정 및 vsphere-csi-controller error 수정
  manifest/hypercloud/hypercloud-capi-vsphere-template.libsonnet
  manifest/hypercloud/hypercloud-multi-operator.jsonnet
Labels: bug
